name: Build ISO Image (self-hosted)

# Avoids having multiple instances running
concurrency:
  group: build-iso-self-hosted
  cancel-in-progress: true

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  image_name: "VNOI Ubuntu ${{ github.ref }}"

jobs:
  build:
    name: Build and push image
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Write authorized_keys
        run: echo $CONTENT | base64 -d > $FILENAME
        env:
          CONTENT: ${{ secrets.AUTHORIZED_KEYS }}
          FILENAME: src/misc/authorized_keys

      - name: Write config.local.sh
        run: echo $CONTENT | base64 -d > $FILENAME
        env:
          CONTENT: ${{ secrets.CONFIG_LOCAL_SH }}
          FILENAME: config.local.sh

      - name: Write src/config.local.sh
        run: echo $CONTENT | base64 -d > $FILENAME
        env:
          CONTENT: ${{ secrets.SRC_CONFIG_LOCAL_SH }}
          FILENAME: src/config.local.sh

      - name: Write src/config.sh
        run: echo $CONTENT | base64 -d > $FILENAME
        env:
          CONTENT: ${{ secrets.SRC_CONFIG_SH }}
          FILENAME: src/config.sh

      - name: Build image
        run: sudo ./build.sh icpc_build --github-actions

      # ----------------------- #
      # Push to Github Releases #
      # ----------------------- #
      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ github.event.inputs.generate_iso == 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.image_name }}
          draft: false
          prerelease: false
