name: Build ISO Image (self-hosted runner & storage)

# Avoids having multiple instances running
concurrency:
  group: build-iso-self-hosted
  cancel-in-progress: true

on:
  workflow_dispatch:

env:
  image_name: "VNOI Ubuntu ${{ github.ref }}"

jobs:
  build:
    name: Build and push image
    runs-on: self-hosted

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-docker-images: 'true'
          remove-codeql: 'true'
          remove-haskell: 'true'
          remove-android: 'true'

      - name: Check free space
        run: echo "Free space $(df -h /)"

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Write authorized_keys
        run: echo $CONTENT | base64 -d > $FILENAME
        env:
          CONTENT: ${{ secrets.AUTHORIZED_KEYS }}
          FILENAME: image-toolkit/misc/authorized_keys

      - name: Write config.local.sh
        run: echo $CONTENT | base64 -d > $FILENAME
        env:
          CONTENT: ${{ secrets.CONFIG_LOCAL_SH }}
          FILENAME: config.local.sh

      - name: Write image-toolkit/config.sh
        run: echo $CONTENT | base64 -d > $FILENAME
        env:
          CONTENT: ${{ secrets.TOOLKIT_CONFIG_SH }}
          FILENAME: image-toolkit/config.sh

      - name: Build image
        run: sudo ./build.sh icpc_build --github-actions
