name: Build ISO Image (Releases)

# Avoids having multiple instances running
concurrency:
  group: build-iso
  cancel-in-progress: true

on:
  push:
    tags:
      - 'v*'

env:
  image_name: "VNOI Ubuntu ${{ github.ref }}"

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Write authorized_keys
        run: echo $CONTENT | base64 -d > $FILENAME
        env:
          CONTENT: ${{ secrets.AUTHORIZED_KEYS }}
          FILENAME: image-toolkit/misc/authorized_keys

      - name: Write config.local.sh
        run: echo $CONTENT | base64 -d > $FILENAME
        env:
          CONTENT: ${{ secrets.CONFIG_LOCAL_SH }}
          FILENAME: config.local.sh

      - name: Write image-toolkit/config.local.sh
        run: echo $CONTENT | base64 -d > $FILENAME
        env:
          CONTENT: ${{ secrets.SRC_CONFIG_LOCAL_SH }}
          FILENAME: image-toolkit/config.local.sh

      - name: Write image-toolkit/config.sh
        run: echo $CONTENT | base64 -d > $FILENAME
        env:
          CONTENT: ${{ secrets.SRC_CONFIG_SH }}
          FILENAME: image-toolkit/config.sh

      - name: Build image
        run: sudo ./build.sh icpc_build --github-actions

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.image_name }}
          draft: false
          prerelease: false
      
      - name: Split ISO
        run: mkdir iso-parts; split -b 2000MB live-build/contestant.iso iso-parts/contestant

      - name: Upload ISO
        uses: softprops/action-gh-release@v1
        with:
          files: iso-parts/contestant*
